### ISSUE TITLE
specify versioning of imported modules

### ISSUE THREAD

**Issue by emited** [mfinzi/constrained-hamiltonian-neural-networks#5]
Hi, 

First off, thanks a lot for putting the code online. However, I'm having a hard time re-running the code from my machine: this is due to wrong versioning of modules such as pytorch, pytorch-lightning, etc (the code no longer runs with the more recent versions of these modules). I was wondering if it were possible to specify the versions you used?

Thanks in advance and have a great day,
Emmanuel

**Comment by mfinzi** [comment]
Hi Emmanual,
I'm sorry you're having versioning issues and yes we should have specified the versions from the start. I believe the versions we used were likely pytorch 1.4 (CUDA 10.1), and pytorch-lightning 0.7.0 (though possibly 0.6.0 I'm not 100% sure).
Let me know if this works for you 
- Marc

**Comment by emited** [comment]
Thanks a lot for your help!
